const
	ABOUT_LINES = 28;
end
global
	string about_text[ABOUT_LINES] = 
	"Monkey Vs Robots by Pixelatom",
	" ",
	"Idea, programming and pixelart by",
	"Lautaro Fernandez, Javier Arias", 
	"and Lucas Zallio",
	" ",
	"Motion Tween lib by Ruben Dopazo",
	" ",
	"Made with BennuGD (bennugd.org)",
	"iOS, Android & OUYA ports thanks",
	"to Joseba Garcia Etxebarria,",
	"Open Pandora port by GECA soft",
	" ",
	"Title Image:", 
	"imroger (imroger.deviantart.com)",
	" ",
	"Music &sounds:",	
	"'2013_07' by Luis Lopez Martinez",
	"'Chee Zee Jungle' by Kevin MacLeod",
	"'Tafi Maradi' by Kevin MacLeod",
	"'HackBeat' by Kevin MacLeod",
	"'Tropical Musical Sound 3' and", 
	"'Pizzicato Orchestral Roll 1'", 
	"by Soughtafter Sounds",
	"'Gewonnen2' by Kastenfrosch" ,
	"'swosh' by qubodup",
	" ",
	"Fonts:",
	"'Gooddog' by Fonthead Design",
	int about_map;
end
