set_property(GLOBAL PROPERTY FIND_LIBRARY_USE_LIB64_PATHS OFF)

add_definitions(-DVERSION="1.0.0")
add_definitions(-D__MONOLITHIC__)

if(NO_MODCHIPMUNK)
    add_definitions(-DNO_MODCHIPMUNK -DCP_USE_DOUBLES=0)
endif(NO_MODCHIPMUNK)
if(NO_MODICONV)
    add_definitions(-DNO_MODICONV)
endif(NO_MODICONV)
if(NO_MODSTEAM)
    add_definitions(-DNO_MODSTEAM)
endif(NO_MODSTEAM)
if(NO_MODCURL)
    add_definitions(-DNO_MODCURL)
endif(NO_MODCURL)
if(NO_MODMEM)
    add_definitions(-DNO_MODMEM)
endif(NO_MODMEM)
if(NO_MODFSOCK)
    add_definitions(-DNO_MODFSOCK)
endif(NO_MODFSOCK)
if(NO_MODMULTI)
    add_definitions(-DNO_MODMULTI)
endif(NO_MODMULTI)
if(NO_MODDEBUG)
    add_definitions(-DNO_MODDEBUG)
endif(NO_MODDEBUG)
if(NO_MODTHEORA)
    add_definitions(-DNO_MODTHEORA)
endif(NO_MODTHEORA)
if(NO_MODEFFECTS)
    add_definitions(-DNO_MODEFFECTS)
endif(NO_MODEFFECTS)
if(NO_MODREGEX)
    add_definitions(-DNO_MODREGEX)
endif(NO_MODREGEX)
if(NO_MODSQLITE)
    add_definitions(-DNO_MODSQLITE)
endif(NO_MODSQLITE)
if(NO_MODNSWITCH)
    add_definitions(-DNO_MODNSWITCH)
endif(NO_MODNSWITCH)
if(NO_MODSHADER)
    add_definitions(-DNO_MODSHADER)
endif(NO_MODSHADER)

if(EMSCRIPTEN)
    add_definitions(-DNO_JPEG)
    add_definitions(-DNO_WEBP)
    add_definitions(-DNO_MODSHADER)
endif(EMSCRIPTEN)

if(NO_SDL_RUMBLE)
    add_definitions(-DDISABLE_RUMBLE)
endif(NO_SDL_RUMBLE)