find_package(SDL2 2.0.4 REQUIRED)
find_package(SDL2_Mixer REQUIRED)
find_package(ZLIB REQUIRED)
find_package(PNG REQUIRED)
find_package(JPEG REQUIRED)
find_package(WEBP REQUIRED)
find_package(OGG REQUIRED)
find_package(Freetype REQUIRED)

if(NOT NO_MODTHEORA)
	find_package(Theora REQUIRED)
	find_package(OpenAL REQUIRED)
	find_package(Vorbis REQUIRED)
endif(NOT NO_MODTHEORA)
if(NOT NO_MODREGEX)
	find_package(TRE REQUIRED)
endif(NOT NO_MODREGEX)
if(NOT NO_MODCURL)
	find_package(CURL REQUIRED)
endif(NOT NO_MODCURL)
if(NOT NO_MODSTEAM)
	find_package(STEAMWORKS REQUIRED)
endif(NOT NO_MODSTEAM)
