if(DEFINED ENV{VITASDK})
    set(CMAKE_TOOLCHAIN_FILE "$ENV{VITASDK}/share/vita.toolchain.cmake" CACHE PATH "toolchain file")
    include("$ENV{VITASDK}/share/vita.cmake" REQUIRED)
    add_definitions(-DTARGET_VITA)
endif(DEFINED ENV{VITASDK})

if(NOT EMSCRIPTEN)
    find_package(SDL2 2.0.4 REQUIRED)
    find_package(SDL2_mixer REQUIRED)
    find_package(ZLIB REQUIRED)
    find_package(PNG REQUIRED)
    find_package(OGG REQUIRED)
    find_package(VORBIS REQUIRED)
    find_package(Freetype REQUIRED)
    find_package(JPEG REQUIRED)
    find_package(WEBP REQUIRED)
	
	if(NOT NO_MODCHIPMUNK)
		find_package(CHIPMUNK REQUIRED)
	endif(NOT NO_MODCHIPMUNK)

    if(NOT NO_MODSHADER)
        find_package(OpenGL REQUIRED)
        find_package(OPENGLES2 REQUIRED)
    endif(NOT NO_MODSHADER)

    if(NOT NO_MODTHEORA)
        find_package(OpenAL REQUIRED)
        find_package(Theora REQUIRED)
    endif(NOT NO_MODTHEORA)

    if(NOT NO_MODREGEX)
        find_package(TRE REQUIRED)
    endif(NOT NO_MODREGEX)

    if(NOT NO_MODCURL)
        find_package(CURL REQUIRED)
    endif(NOT NO_MODCURL)

    if(NOT NO_MODSTEAM)
        find_package(STEAMWORKS REQUIRED)
    endif(NOT NO_MODSTEAM)
endif(NOT EMSCRIPTEN)