#!/bin/bash

cd "$(dirname $0)"

rm -rf build
rm -f main
rm -f bgdrtm.a
cd ../../core
for i in $(find * | grep "\.o"); do rm $i; done
cd ../modules
for i in $(find * | grep "\.o"); do rm $i; done
echo "Done"
